// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdHEotdwUpyfw9PxBVTBfbKcGDOfpJHTo',
    appId: '1:927542335283:web:c71397fd0556a6674c5046',
    messagingSenderId: '927542335283',
    projectId: 'project-lamplight-a1a40',
    authDomain: 'project-lamplight-a1a40.firebaseapp.com',
    storageBucket: 'project-lamplight-a1a40.appspot.com',
    measurementId: 'G-5VDS8Y3GS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcAOoGNLAVQ9-Bvr4ztIHuOyJu1FAIDw',
    appId: '1:927542335283:android:e499ad20425445fa4c5046',
    messagingSenderId: '927542335283',
    projectId: 'project-lamplight-a1a40',
    storageBucket: 'project-lamplight-a1a40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4y6_9g9cwfd3XBGxj3IBoAH5m2Evw2QY',
    appId: '1:927542335283:ios:c10244837fa4f4a14c5046',
    messagingSenderId: '927542335283',
    projectId: 'project-lamplight-a1a40',
    storageBucket: 'project-lamplight-a1a40.appspot.com',
    iosClientId: '927542335283-riki4qdaldcepf9mrgielcnqj6dredat.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectLamplight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4y6_9g9cwfd3XBGxj3IBoAH5m2Evw2QY',
    appId: '1:927542335283:ios:4f767dd62846bd124c5046',
    messagingSenderId: '927542335283',
    projectId: 'project-lamplight-a1a40',
    storageBucket: 'project-lamplight-a1a40.appspot.com',
    iosClientId: '927542335283-fvcnen5vdccihcod5kvtpdovfh2mrcr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectLamplight.RunnerTests',
  );
}
